=== Stillix/XmlTask/data_xml/TouristVouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/TouristVouchers"
        xmlns:tns="http://www.example.org/TouristVouchers">

    <element name="TouristVouchers">
        <complexType>
            <sequence>
                <element name="Voucher" type="tns:Voucher" maxOccurs="unbounded" minOccurs="1"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Voucher">
        <sequence>
            <element name="VoucherType" type="tns:VoucherType"/>
            <element name="Country" type="string"/>
            <element name="Transport" type="tns:TransportType"/>
            <element name="NumberDays" type="positiveInteger"/>
            <element name="ArrivalDate" type="dateTime"/>
            <element name="Hotel">
                <complexType>
                    <choice>
                        <element name="BasicHotelCharacteristics" type="tns:BasicHotelCharacteristics"/>
                        <element name="ExclusiveCharacteristics" type="tns:ExclusiveCharacteristics"/>
                    </choice>
                </complexType>
            </element>
            <element name="Cost"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>

    <simpleType name="VoucherType">
        <restriction base="string">
            <enumeration value="Recreation Voucher"></enumeration>
            <enumeration value="Health Voucher"></enumeration>
            <enumeration value="Guided Tour Voucher"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="TransportType">
        <restriction base="string">
            <enumeration value="avia"></enumeration>
            <enumeration value="avto"></enumeration>
            <enumeration value="liner"></enumeration>
            <enumeration value="train"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="BasicHotelCharacteristics">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Star" type="tns:StarType"/>
            <element name="Food" type="tns:FoodType"/>
            <element name="Room" type="tns:Apartment"/>
        </sequence>
    </complexType>

    <complexType name="Apartment">
        <sequence>
            <element name="TV" type="boolean"/>
            <element name="Conditioner" type="boolean"/>
            <element name="RoomAmount" type="tns:RoomAmount"/>
        </sequence>
        <attribute name="WIFI" type="boolean"/>
        <attribute name="Balcony" type="boolean"/>
    </complexType>

    <complexType name="ExclusiveCharacteristics">
        <complexContent>
            <extension base="tns:BasicHotelCharacteristics">
                <sequence>
                    <element name="Services" type="tns:Services"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Services">
        <restriction base="string">
            <enumeration value="Bar, Swimming Pool, Fitness Center,parking"></enumeration>
            <enumeration value="Bar"></enumeration>
            <enumeration value="Fitness Center"></enumeration>
            <enumeration value="Parking"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="StarType">
        <restriction base="positiveInteger">
            <enumeration value="1"></enumeration>
            <enumeration value="2"></enumeration>
            <enumeration value="3"></enumeration>
            <enumeration value="4"></enumeration>
            <enumeration value="5"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="RoomAmount">
        <restriction base="integer">
            <pattern value="[1-3]{1}"/>
        </restriction>
    </simpleType>

    <simpleType name="FoodType">
        <restriction base="string">
            <enumeration value="BB"></enumeration>
            <enumeration value="HB"></enumeration>
            <enumeration value="FB"></enumeration>
            <enumeration value="AL"></enumeration>
        </restriction>
    </simpleType>

</schema>

=== Stillix/XmlTask/data_xml/TouristVouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:TouristVouchers xmlns:tns="http://www.example.org/TouristVouchers"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://www.example.org/TouristVouchers TouristVouchers.xsd ">
    <Voucher id="vch1">
        <VoucherType>Recreation Voucher</VoucherType>
        <Country>Spain</Country>
        <Transport>avia</Transport>
        <NumberDays>9</NumberDays>
        <ArrivalDate>2023-05-30T09:00:00</ArrivalDate>
        <Hotel>
            <BasicHotelCharacteristics>
                <Name>Serras Barcelona</Name>
                <Star>3</Star>
                <Food>BB</Food>
                <Room WIFI="false" Balcony="false">
                    <TV>false</TV>
                    <Conditioner>false</Conditioner>
                    <RoomAmount>3</RoomAmount>
                </Room>
            </BasicHotelCharacteristics>
        </Hotel>
        <Cost>730</Cost>
    </Voucher>

    <Voucher id="vch2">
        <VoucherType>Guided Tour Voucher</VoucherType>
        <Country>France</Country>
        <Transport>avto</Transport>
        <NumberDays>9</NumberDays>
        <ArrivalDate>2023-07-14T17:40:00</ArrivalDate>
        <Hotel>
            <ExclusiveCharacteristics>
                <Name>Mercer Hotel Barcelona</Name>
                <Star>5</Star>
                <Food>FB</Food>
                <Room Balcony="true" WIFI="true">
                    <TV>true</TV>
                    <Conditioner>true</Conditioner>
                    <RoomAmount>2</RoomAmount>
                </Room>
                <Services>Bar, Swimming Pool, Fitness Center,parking</Services>
            </ExclusiveCharacteristics>
        </Hotel>
        <Cost>1500</Cost>
    </Voucher>

</tns:TouristVouchers>
