=== Stillix/XmlTask/src/main/resources/TouristVouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/TouristVouchers"
        xmlns:tns="http://www.example.org/TouristVouchers">

    <element name="TouristVouchers">
        <complexType>
            <sequence>
                <element name="Voucher" type="tns:Voucher" maxOccurs="unbounded" minOccurs="1"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Voucher">
        <sequence>
            <element name="VoucherType" type="tns:VoucherType"/>
            <element name="Country" type="string"/>
            <element name="Transport" type="tns:TransportType"/>
            <element name="NumberDays" type="positiveInteger"/>
            <element name="NumberNights" type="positiveInteger"/>
            <element name="Hotel">
                <complexType>
                    <choice>
                        <element name="BasicHotelCharacteristics" type="tns:BasicHotelCharacteristics"/>
                        <element name="ExclusiveCharacteristics" type="tns:ExclusiveCharacteristics"/>
                    </choice>
                </complexType>
            </element>
            <element name="Cost"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>

    <simpleType name="VoucherType">
        <restriction base="string">
            <enumeration value="Recreation Voucher"></enumeration>
            <enumeration value="Health Voucher"></enumeration>
            <enumeration value="Guided Tour Voucher"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="TransportType">
        <restriction base="string">
            <enumeration value="avia"></enumeration>
            <enumeration value="avto"></enumeration>
            <enumeration value="liner"></enumeration>
            <enumeration value="train"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="BasicHotelCharacteristics">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Star" type="tns:StarType"/>
            <element name="Food" type="tns:FoodType"/>
            <element name="Room" type="tns:Apartment"/>
        </sequence>
    </complexType>

    <complexType name="Apartment">
        <sequence>
            <element name="TV" type="boolean"/>
            <element name="Conditioner" type="boolean"/>
            <element name="RoomAmount" type="tns:RoomAmount"/>
        </sequence>
        <attribute name="Balcony" type="boolean"/>
    </complexType>

    <complexType name="ExclusiveCharacteristics">
        <complexContent>
            <extension base="tns:BasicHotelCharacteristics">
                <sequence>
                    <element name="Sport" type="tns:SportType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="SportType">
        <restriction base="string">
            <enumeration value="BasketSquare"></enumeration>
            <enumeration value="VolleyballSquare"></enumeration>
            <enumeration value="Gym"></enumeration>
            <enumeration value="Gym,VolleyballSquare,BasketSquare"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="StarType">
        <restriction base="integer">
            <pattern value="[1-5]"/>
        </restriction>
    </simpleType>

    <simpleType name="RoomAmount">
        <restriction base="integer">
            <pattern value="[1-3]{1}"/>
        </restriction>
    </simpleType>

    <simpleType name="FoodType">
        <restriction base="string">
            <enumeration value="BB"></enumeration>
            <enumeration value="HB"></enumeration>
            <enumeration value="FB"></enumeration>
            <enumeration value="AL"></enumeration>
        </restriction>
    </simpleType>

</schema>

=== Stillix/XmlTask/src/main/resources/TouristVouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:TouristVouchers xmlns:tns="http://www.example.org/TouristVouchers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/TouristVouchers TouristVouchers.xsd ">

    <Voucher id="1">
        <VoucherType>Recreation Voucher</VoucherType>
        <Country>France</Country>
        <Transport>train</Transport>
        <NumberDays>9</NumberDays>
        <NumberNights>8</NumberNights>
        <Hotel>
            <BasicHotelCharacteristics>
                <Name> </Name>
                <Star>4</Star>
                <Food>HB</Food>
                <Room>1</Room>
            </BasicHotelCharacteristics>
        </Hotel>
        <Cost>500</Cost>
    </Voucher>

    <Voucher id="2">
        <VoucherType>Recreation Voucher</VoucherType>
        <Country>Spain</Country>
        <Transport>avia</Transport>
        <NumberDays> </NumberDays>
        <NumberNights> </NumberNights>
        <Hotel>
            <ExclusiveHotelCharacteristics>
                <Name> </Name>
                <Star>5</Star>
                <Food>FB</Food>
                <Room>2</Room>
                <Sport>Gym,VolleyballSquare,BasketSquare</Sport>
            </ExclusiveHotelCharacteristics>
        </Hotel>
        <Cost>1135</Cost>
    </Voucher>
</tns:TouristVouchers>
